{% set name = "equilibrator-cache" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f08e8417e91381cf6a9cffac0ea549780b7d2036807e5a8213d0a9884e2518a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=62.6
    - setuptools-scm
    - setuptools-git-versioning >=2.0,<3
  run:
    - python >={{ python_min }}
    - sqlalchemy ~=2.0
    - numpy >=2.0
    - scipy >=1.12
    - pandas >=2.0
    - pyarrow ~=17.0
    - Levenshtein ~=0.25
    - pint ~=0.24
    - tqdm ~=4.0
    - appdirs ~=1.4
    - pooch ~=1.8

test:
  imports:
    - equilibrator_cache
    - equilibrator_cache.models
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://gitlab.com/elad.noor/equilibrator-cache
  summary: Cache application for compounds, reactions, and enzymes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rgiessmann
    - Midnighter
    - eladnoor
