{% set name = "equilibrator-cache" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-cache-{{ version }}.tar.gz
  sha256: 391e860085354715c60593b5a97874b1cb7ee43148072a645623ecc6f79d9e96
  patches:
    - 0001-Setuptools-depend-on-python-Levenshtein-instead-of-p.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs ~=1.4
    - httpx ~=0.16
    - importlib_resources
    - numpy ~=1.19
    - pandas ~=1.0
    - periodictable ~=1.5
    - pint ~=0.14
    - python >=3.6
    - python-levenshtein
    - pyzenodo3 ~=1.0
    - scipy ~=1.5
    - sqlalchemy >=1.3, <1.4
    - tenacity ~=6.2
    - tqdm ~=4.50

test:
  imports:
    - equilibrator_cache
    - equilibrator_cache.models
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/elad.noor/equilibrator-cache
  summary: Cache application for compounds, reactions, and enzymes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Midnighter
    - eladnoor
