{% set name = "equilibrator-cache" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 34e040c2fe27c6ad4ba815f50b1ce1d01c119025e60a1f56dc84f8d81b4fe7c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - sqlalchemy ~=2.0
    - numpy >=1.13
    - scipy >=1.11
    - pandas >=2.0
    - pyarrow ~=15.0
    - Levenshtein ~=0.21
    - pint ~=0.22
    - tqdm ~=4.0
    - appdirs ~=1.4
    - pooch ~=1.8

test:
  imports:
    - equilibrator_cache
    - equilibrator_cache.models
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/elad.noor/equilibrator-cache
  summary: Cache application for compounds, reactions, and enzymes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rgiessmann
    - Midnighter
    - eladnoor
