{% set name = "equilibrator-cache" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-cache-{{ version }}.tar.gz
  sha256: 1372456a3e188eb0b580de4eda0c7181266c47f1f8abde2d425ab3fbf955b76a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - sqlalchemy >=1.3,<1.4
    - numpy >=1.13
    - pandas >=1.5
    - Levenshtein ~=0.21
    - pint ~=0.22
    - periodictable ~=1.5
    - httpx ~=0.24
    - requests ~=2.31
    - tenacity ~=6.3
    - tqdm ~=4.0
    - appdirs ~=1.4

test:
  imports:
    - equilibrator_cache
    - equilibrator_cache.models
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/elad.noor/equilibrator-cache
  summary: Cache application for compounds, reactions, and enzymes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rgiessmann
    - Midnighter
    - eladnoor
