{% set name = "equilibrator-cache" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-cache-{{ version }}.tar.gz
  sha256: 7e692d33937237eb5921824e85e546b2024bb3f6ec01ddd92ab8c46dcc88ef5e
  patches:
    - 0001-Setuptools-depend-on-python-Levenshtein-instead-of-p.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - appdirs ~=1.4
    - httpx ~=0.24
    - numpy >=1.13
    - pandas ~=1.0
    - periodictable ~=1.6
    - pint ~=0.22
    - python >=3.9
    - python-levenshtein ~=0.21
    - scipy >=1.11
    - sqlalchemy >=1.3, <1.4
    - tenacity ~=6.3
    - tqdm ~=4.0

test:
  imports:
    - equilibrator_cache
    - equilibrator_cache.models
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/elad.noor/equilibrator-cache
  summary: Cache application for compounds, reactions, and enzymes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Midnighter
    - eladnoor
